#!/bin/sh

. ./ci-vars.sh
. ./scripts/common-functions.sh

ROOT=$(pwd)
BUILD_DIR=${ROOT}/build
echo "${0}: BUILD_DIR - ${BUILD_DIR}"

# prepare some common args:
# get compiler version
CMAKE_DEFAULT_ARGS="${ADDL_CMAKE_FLAGS}"

INSTALL_PATH=$(get_install_path ${BUILD_DIR})

### build openfhe-development
OPENFHE_REPO="https://github.com/openfheorg/openfhe-development.git"
OPENFHE_DIR="${BUILD_DIR}/openfhe-development"
OPENFHE_INSTALL_DIR="${INSTALL_PATH}/openfhe-development"
OPENFHE_CMAKE_ARGS=${CMAKE_DEFAULT_ARGS}" -DCMAKE_INSTALL_PREFIX=${OPENFHE_INSTALL_DIR}"
OPENFHE_CMAKE_ARGS=${OPENFHE_CMAKE_ARGS}" -DBUILD_STATIC=OFF -DBUILD_SHARED=ON"
OPENFHE_CMAKE_ARGS=${OPENFHE_CMAKE_ARGS}" -DBUILD_BENCHMARKS=OFF -DBUILD_UNITTESTS=OFF -DBUILD_EXAMPLES=OFF"

clone ${OPENFHE_REPO} ${OPENFHE_DIR}
build_install_tag_with_args ${OPENFHE_DIR} ${OPENFHE_TAG} "${OPENFHE_CMAKE_ARGS}" ${PARALELLISM}

### build openfhe-python
OPENFHE_PYTHON_REPO="https://github.com/openfheorg/openfhe-python.git"
OPENFHE_PYTHON_DIR="${BUILD_DIR}/openfhe-python"
OPENFHE_PYTHON_INSTALL_DIR="${INSTALL_PATH}/openfhe-python"
OPENFHE_PYTHON_CMAKE_ARGS=${CMAKE_DEFAULT_ARGS}" -DCMAKE_INSTALL_PREFIX=${OPENFHE_PYTHON_INSTALL_DIR}"
OPENFHE_PYTHON_CMAKE_ARGS=${OPENFHE_PYTHON_CMAKE_ARGS}" -DCMAKE_PREFIX_PATH=${OPENFHE_INSTALL_DIR}"

clone ${OPENFHE_PYTHON_REPO} ${OPENFHE_PYTHON_DIR}
build_install_tag_with_args ${OPENFHE_PYTHON_DIR} ${OPENFHE_PYTHON_TAG} "${OPENFHE_PYTHON_CMAKE_ARGS}" ${PARALELLISM}

### build openfhe-numpy
OPENFHE_NUMPY_REPO="https://github.com/openfheorg/openfhe-numpy.git"
OPENFHE_NUMPY_DIR="${BUILD_DIR}/openfhe-numpy"
OPENFHE_NUMPY_INSTALL_DIR="${INSTALL_PATH}/openfhe-numpy"
OPENFHE_NUMPY_CMAKE_ARGS=${CMAKE_DEFAULT_ARGS}" -DCMAKE_INSTALL_PREFIX=${OPENFHE_NUMPY_INSTALL_DIR}"
OPENFHE_NUMPY_CMAKE_ARGS=${OPENFHE_NUMPY_CMAKE_ARGS}" -DCMAKE_PREFIX_PATH='${OPENFHE_INSTALL_DIR};${OPENFHE_PYTHON_INSTALL_DIR}'"
# echo "OPENFHE_NUMPY_CMAKE_ARGS: ${OPENFHE_NUMPY_CMAKE_ARGS}"

clone ${OPENFHE_NUMPY_REPO} ${OPENFHE_NUMPY_DIR}
build_install_tag_with_args ${OPENFHE_NUMPY_DIR} ${OPENFHE_NUMPY_TAG} "${OPENFHE_NUMPY_CMAKE_ARGS}" ${PARALELLISM}

separator

